Cover domain logic with unit tests For some reason unit tests can only run from command line: "./gradlew test" Running from Android Studio causes error "java.lang.NoClassDefFoundError: io/mockk/proxy/MockKAgentFactory"